version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=111111222
      - POSTGRES_DB=phonebook
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5442:5432"

  app:
    build:
      context: ./
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/phonebook
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/phonebook
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=111111222
      - POSTGRES_PASSWORD=111111222
      - POSTGRES_DB=phonebook
    ports:
      - "8080:8080"

